export const ACTION_TYPES = {
  GET_USERS: "GET_USERS",
  CREATE_USERS: "CREATE_USERS",
  DELETE_USERS: "DELETE_USERS",

  GET_POSTS: "GET_POSTS",
  UPDATE_POSTS: "UPDATE_POSTS",

  GET_ALL_MESSAGES: "GET_ALL_MESSAGES",
};
